### ISSUE TITLE
Ongoing improvements

### ISSUE THREAD

**Issue by avindra** [avindra/ttt-plusplus#4]
Next:

 * [ ] Decouple core game code from Qt
 * [ ] Tests
 * [ ] Harden impossible mode: can be beaten still in 1 specific way :^)

Nice to have:

 * [ ] Continuous integration
 * [ ] Backport build to Windows<sup>†</sup>

## Notes

<sup>†</sup> The project was bootstrapped with and for Visual Studio 2008, and the story on MS build compatibility is unknown to me. So the build got [moved](https://github.com/avindra/ttt-plusplus/commit/1cddd4c579e94ad69c161635db4d10ed5e19f5af) to `CMake` which is commonly used with Qt projects.
